#!/usr/bin/env python

import rospy, sys, os, time
import string
import warnings

from gazebo_ros import gazebo_interface


if __name__ == "__main__":
	if len(sys.argv) < 2:
		sleep_time = 0.0
	else:
		print sys.argv[1]
		sleep_time = float(sys.argv[1])

	# Defined the variables
	param_name              = ""
	model_name              = ""
	robot_namespace         = ""
	gazebo_namespace        = "/gazebo"
	joint_names             = []
	joint_positions         = []

	# Setting the parameters
	model_name = 'hyl'
	param_name = 'robot_description'
	joint_names.append('slider_joint')
	joint_positions.append(0.)
	joint_names.append('haa_joint')
	joint_positions.append(0.)
	joint_names.append('hfe_joint')
	joint_positions.append(0.75)
	joint_names.append('kfe_joint')
	joint_positions.append(-1.5)


	gazebo_namespace = '/gazebo'
	rospy.wait_for_service('%s/set_model_configuration'%(gazebo_namespace))
	rospy.sleep(sleep_time)
	try:
		success = gazebo_interface.set_model_configuration_client(model_name, param_name, 
                                                                  joint_names, joint_positions, gazebo_namespace)
	except rospy.ServiceException, e:
		print "set model configuration service call failed: %s"%e
